version: "3.3"

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    privileged: true
    tty: true
    environment:
      - MYSQL_DATABASE=achatdb
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - 8089:8089
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: achatdb
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
    links:
      - mysqldb
#  app1:
#    container_name: dockerfile_angular
#
#    ports:
#      - '4200:80'
#    image: 46416514/dev-ops-project-app1
#
#
#
#    restart: always
#    depends_on:
#      - app
volumes:
  db:
#  crud-tuto-front: