version: "3.3"

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    privileged: true
    tty: true
    environment:
      - MYSQL_DATABASE=achatdb
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    ports:
      - 8089:8089
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: .
    restart: on-failure
    env_file: ./.env
    ports:
      - 3306:3306
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqladmin:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE?useSSL=false",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_ROOT_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"}'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
#  app1:
#    container_name: dockerfile_angular
#
#    ports:
#      - '4200:80'
#    image: 46416514/dev-ops-project-app1
#
#
#
#    restart: always
#    depends_on:
#      - app
volumes:
  db:
#  crud-tuto-front: